#%RAML 0.8
---
title: Waste Services API
version: v0.1
baseUri: http://api.council.gov.uk/waste

documentation:
  - title: Introduction
    content: |
      This API offers a core set of resources and operations for interacting with local council waste and recycling services.

  - title: Outstanding issues
    content: |
      * A way to discover if a task has been moved from its regular timeslot and why.
      * Handling of non-property sites, e.g. where the bins are located separately from a building.

  - title: ESD Standards
    content: |
      The [ESD Standards](http://standards.esd.org.uk) define all the categories of services that local authorities typically provide. These will be referenced via URL from the Services API, to allow individual council instances of a service to be matched to common service definitions.

# schemas:
  # - event: !include ../_includes/schemas/waste_event.schema.json
    # events: !include ../schemas/events.json

resourceTypes:
  - collection:
      usage: This resourceType should be used for any collection of items
      description: The collection of <<resourcePathName>>
      get:
        description: Get all <<resourcePathName>>, optionally filtered
      post:
        description: Create a new <<resourcePathName | !singularize>>

traits:
  - paged:
      queryParameters:
        page:
          type: number

/services:
  displayName: Services
  description: A Service is what a council offers to citizens. There are a number of waste and recycling related services offered by most councils.
  type: collection
  get:
    description: Get a list of waste services
    queryParameters:
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
      full:
        type: boolean
        description: Return the full service information.
    responses:
      200:
        body:
          application/json:
            example: !include ../_includes/examples/waste_services.json
  /{serviceId}:
    get:
      description: Get a single service
      queryParameters:
        uprn:
          type: string
          description: Limit results to those related to the property with this UPRN. This will include the last and next collection task information.
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/waste_service.json

/tasks:
  displayName: Tasks
  type: collection
  get:
    description: Get a list of tasks
    # is: [ paged ]
    queryParameters:
      type:
        type: string
        description: Limit results to a specific task type.
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
      date_range:
        type: string
        description: Limit results to those tasks that were started between the given comma-separated date range. Dates should be in xs:dateTime format, e.g. date_range=2015-06-01,2015-08-01.

/event_types:
  displayName: Event types
  type: collection
  get:
    description: Get a list of event types
    responses:
      200:
        body:
          application/json:
            example: !include ../_includes/examples/event_types.json

  /{eventTypeId}:
    get:
      description: Get a single event type
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/event_type.json

/events:
  displayName: Events
  type: collection
  get:
    description: Get a list of events
    # is: [ paged ]
    queryParameters:
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
      usrn:
        type: string
        description: Limit results to those related to the street with this USRN.
      date_range:
        type: string
        description: Limit results to those events that occurred between the given comma-separated date range. Dates should be in xs:dateTime format, e.g. date_range=2015-06-01,2015-08-01.
    responses:
      200:
        body:
          application/json:
            example: !include ../_includes/examples/events.json

  /{eventId}:
    get:
      description: Get a single event
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/waste_event.json

/features:
  displayName: Features
  description: A feature is an item related to a service.
  type: collection
  get:
    description: Get a list of features
    queryParameters:
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
      usrn:
        type: string
        description: Limit results to those related to the street with this USRN.
    # responses:
    #   200:
    #     body:
    #       application/json:
            # example: !include ../_includes/examples/features.json
  /{featureId}:
    get:
      description: Get a single feature
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/feature.json

/feature-types:
  displayName: Feature types
  description: A feature type is a representative of the kinds of items related to a service, for example a waste container used in a waste collection service.
  type: collection
  get:
    description: Get a list of feature types
    queryParameters:
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
    # responses:
    #   200:
    #     body:
    #       application/json:
            # example: !include ../_includes/examples/features.json
  /{featureTypeId}:
    get:
      description: Get a single feature type
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/feature_type.json

/sites:
  displayName: Sites
  description: A site is a place or location where services are provided.
  type: collection
  get:
    description: Get a list of sites
    queryParameters:
      usrn:
        type: string
        description: Limit results to those related to the street with this USRN.
      postcode:
        type: string
        description: Limit results to those with the given postcode.
    responses:
      200:
        body:
          application/json:
            # example: !include ../_includes/examples/sites.json
  /{ID}:
    get:
      description: Get a single site indexed by UPRN, or another form of index if some sites do not have a UPRN. In that situation, the format of other IDs must not collide with UPRNs.
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/site.json

/cases:
  displayName: Cases
  description: A case is a customer interaction record.
  type: collection
  get:
    description: Get a list of cases
    queryParameters:
      uprn:
        type: string
        description: Limit results to cases associated with this UPRN.
      usrn:
        type: string
        description: Limit results to cases within this USRN.
      postcode:
        type: string
        description: Limit results to those with the given postcode.
    responses:
      200:
        body:
          application/json:
            # example: !include ../_includes/examples/cases.json
  post:
    description: Create a new case
  /{caseId}:
    get:
      description: Get a case record
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/case.json

