#%RAML 0.8
---
title: Waste Services API
version: v0.1
baseUri: http://api.council.gov.uk/waste

documentation:
  - title: Introduction
    content: |
      This API offers a core set of resources and operations for interacting with local council waste and recycling services.

  - title: ESD Standards
    content: |
      The [ESD Standards](http://standards.esd.org.uk) define all the categories of services that local authorities typically provide. These will be referenced via URL from the Services API, to allow individual council instances of a service to be matched to common service definitions.

schemas:
  - event: !include ../_includes/schemas/waste_event.schema.json
    # events: !include ../schemas/events.json

resourceTypes:
  - collection:
      usage: This resourceType should be used for any collection of items
      description: The collection of <<resourcePathName>>
      get:
        description: Get all <<resourcePathName>>, optionally filtered
      post:
        description: Create a new <<resourcePathName | !singularize>>

traits:
  - paged:
      queryParameters:
        page:
          type: number

/services:
  displayName: Services
  description: A Service is what a council offers to citizens. There are a number of waste and recycling related services offered by most councils.
  type: collection
  get:
    description: Get a list of waste services
    queryParameters:
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
    # responses:
    #   200:
    #     body:
          # application/json:
            # example: !include ../_includes/examples/services.json
  /{serviceId}:
    get:
    description: Get a single service
    responses:
      200:
        body:
          application/json:
            example: !include ../_includes/examples/waste_service.json

/tasks:
  displayName: Tasks
  type: collection
  get:
    description: Get a list of tasks
    is: [ paged ]
    queryParameters:
      type:
        type: string
        description: Limit results to a specific task type.
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
      date_range:
        type: string
        description: Limit results to those tasks that were started between the given comma-separated date range. Dates should be in xs:dateTime format, e.g. date_range=2015-06-01,2015-08-01.

/events:
  displayName: Events
  type: collection
  get:
    description: Get a list of events
    is: [ paged ]
    queryParameters:
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
      usrn:
        type: string
        description: Limit results to those related to the street with this USRN.
      start_date:
        type: date
        description: Limit results to those created on or after this start date.
      end_date:
        type: date
        description: Limit results to those created before this end date.
    responses:
      200:
        body:
          application/json:
            example: !include ../_includes/examples/events.json

  /{eventId}:
    get:
      description: Get a single event
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/waste_event.json

/features:
  displayName: Features
  description: A feature is an item related to a service.
  type: collection
  get:
    description: Get a list of features
    queryParameters:
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
      usrn:
        type: string
        description: Limit results to those related to the street with this USRN.
    # responses:
    #   200:
    #     body:
    #       application/json:
            # example: !include ../_includes/examples/features.json
  /{featureId}:
    get:
      description: Get a single feature
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/feature.json

/sites:
  displayName: Sites
  description: A site is a place or location where services are provided.
  type: collection
  get:
    description: Get a list of sites
    queryParameters:
      usrn:
        type: string
        description: Limit results to those related to the street with this USRN.
      postcode:
        type: string
        description: Limit results to those with the given postcode.
    responses:
      200:
        body:
          application/json:
            # example: !include ../_includes/examples/sites.json
  /{UPRN}:
    get:
      description: Get a single site indexed by UPRN
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/site.json

/cases:
  displayName: Cases
  description: A case is a customer interaction record.
  type: collection
  get:
    description: Get a list of cases
    queryParameters:
      uprn:
        type: string
        description: Limit results to cases associated with this UPRN.
      usrn:
        type: string
        description: Limit results to cases within this USRN.
      postcode:
        type: string
        description: Limit results to those with the given postcode.
    responses:
      200:
        body:
          application/json:
            # example: !include ../_includes/examples/cases.json
  post:
    description: Create a new case
  /{caseId}:
    get:
      description: Get a case record
      responses:
        200:
          body:
            application/json:
              example: !include ../_includes/examples/case.json

