#%RAML 0.8
---
title: Waste Services API
version: v0.1
baseUri: http://api.council.gov.uk/waste

documentation:
  - title: Introduction
    content: |
      This API offers a core set of resources and operations for interacting with local council waste and recycling services.

  - title: ESD Standards
    content: |
      The [ESD Standards](http://standards.esd.org.uk) define all the categories of services that local authorities typically provide. These will be referenced via URL from the Services API, to allow individual council instances of a service to be matched to common service definitions.

schemas:
  - event: !include ../schemas/waste_event.schema.json
    # events: !include ../schemas/events.json

resourceTypes:
  - collection:
      usage: This resourceType should be used for any collection of items
      description: The collection of <<resourcePathName>>
      get:
        description: Get all <<resourcePathName>>, optionally filtered
      post:
        description: Create a new <<resourcePathName | !singularize>>

traits:
  - paged:
      queryParameters:
        page:
          type: number

/services:
  displayName: Services
  description: A Service is what a council offers to citizens. There are a number of waste and recycling related services offered by most councils.
  type: collection
  get:
    description: Get a list of waste services
    # responses:
    #   200:
    #     body:
          # application/json:
            # example: !include ../examples/services.json
  /{serviceId}:
    get:
    description: Get a single service
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/service.json


/events:
  displayName: Events
  type: collection
  get:
    description: Get a list of events
    is: [ paged ]
    queryParameters:
      uprn:
        type: string
        description: Limit results to those related to the property with this UPRN.
      usrn:
        type: string
        description: Limit results to those related to the street with this USRN.
      type:
        type: string
        description: Limit results to those with a matching type, e.g. "Not presented".
      start_date:
        type: date
        description: Limit results to those created on or after this start date.
      end_date:
        type: date
        description: Limit results to those created before this end date.
      round:
        type: string
        description: Limit results to those recorded against this round.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/events.json

  /{eventId}:
    get:
      description: Get a single event
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/event.json

/round-plans:
  displayName: Round plans
  description: A [Round plan](/models/round-plan.md) describes a route on which a set of containers are processed and the schedule it runs on.
  type: collection
  get:
    description: Get a list of [round plans](/models/round-plan)
    # responses:
    #   200:
    #     body:
    #       application/json:
            # example: !include ../examples/rounds.json
  /{roundId}:
    get:
      description: Get a single round plan
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/round_plan.json

/rounds:
  displayName: Rounds
  description: A Round is a execution of a Round plan on a given day.
  type: collection
  get:
    description: Get a list of [rounds](/models/round)
    responses:
      200:
        body:
          application/json:
            # example: !include ../examples/rounds.json
  /{roundId}:
    get:
      description: Get a single round
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/round.json

/material-streams:
  displayName: Material streams
  description: A material stream is a type of materials that can be collected.
  type: collection
  get:
    description: Get a list of [material streams](/models/material-streams)
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/material_streams.json
  /{streamId}:
    get:
      description: Get a single material stream
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/material_stream.json







